# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'BitOP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BitOP

	pod 'Starscream', '~> 3'
	pod 'KeychainAccess', '~> 3.1.2'
	pod 'NotificationBannerSwift', '~> 1.8.0'
	pod 'IQKeyboardManagerSwift', '~> 6.2.0'
	pod 'Alamofire' 
 target 'BitOPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BitOPUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
